#                            #
# Starship Config by a3chron #
#                            #

palette = "catppuccin_mocha"

# custom format
format = """
[╭─ $shell─────────────── $memory_usage ──╌╌ $nodejs$python$golang$ocaml $fill ╌╌─╮](overlay0)
[├╌](overlay0)$sudo$username$hostname$localip$directory$read_only$git_branch$git_metrics [$fill $cmd_duration ┘](overlay0)
[╰─ $battery $character](overlay0) """

#format = '$all$directory$character'
 
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
command_timeout = 500
add_newline = true

# Catppuchin Theme

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
 
 
[shell]
fish_indicator = 'fish'
bash_indicator = 'bash'
unknown_indicator = 'unknwn'
style = 'green'
disabled = false
 
[username]
style_user = 'green bold'
format = ' [$user@]($style)'
disabled = false
show_always = true
 
[sudo]
format = ' [sudo](bold red)'
disabled = false
 
[python]
symbol = ''
format = '[Python](bold yellow) [$version [\($virtualenv\)](dimmed yellow)](dimmed yellow)'
pyenv_version_name = true
detect_files = ['requirements.txt', '__init.py__', 'setup.py']
detect_extensions = ['py']
detect_folders = []
 
[nodejs]
format = '[Node](bold yellow) [$version](bold dimmed yellow) '

[golang]
format = '[Go](bold yellow) [$version](bold dimmed yellow) '

[ocaml]
format = '[Ocaml](bold yellow) [$version](bold dimmed yellow) '
 
[memory_usage]
disabled = false
threshold = -1
format = '[$ram_pct]($style)'
symbol = ''
style = 'dimmed yellow'
 
[localip]
ssh_only = false
format = '[@$localipv4](bold dimmed yellow) '
disabled = false
 
[hostname]
ssh_only = false
ssh_symbol = 'ssh:'
format = '[$ssh_symbol](bold dimmed maroon)[$hostname](bold dimmed green)'
trim_at = ''
disabled = false
 
[git_metrics]
disabled = false
format = ' [+$added](bold green)[-$deleted](bold maroon)'
 
[git_branch]
format = '[$branch(:$remote_branch)]($style)'
style = 'bold dimmed teal'
 
[fill]
symbol = ' '
style = 'bold base'
 
# time of command
[cmd_duration]
min_time = 500
format = ' [$duration](bold dimmed yellow)'
 
[directory]
fish_style_pwd_dir_length = 5
disabled = false
truncation_length = 5
truncation_symbol = '…/'
read_only = ' read-only'
read_only_style = 'bold dimmed yellow'
style = 'bold yellow'
 
# prompt char
[character]
success_symbol = '[──╌╌](overlay0)'
error_symbol = '[──╌╌](red)'
 
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
 
 
# battery 
[battery]

full_symbol = '● '
charging_symbol = '◉ '
discharging_symbol = '◯ '

[[battery.display]]
threshold = 20
style = 'red'
 
[[battery.display]]
threshold = 100
style = 'green'

